from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from server.models.metrics import EpidemiologicalMetrics

class ReportRequest(BaseModel):
    query: str = Field(..., description="The main text query asking for epidemiological data")
    filters: Optional[Dict[str, Any]] = Field(default=None, description="Optional filters like start_date, end_date, and state (uf)")

class ChartData(BaseModel):
    daily_chart: List[Dict[str, Any]] = Field(default_factory=list)
    monthly_chart: List[Dict[str, Any]] = Field(default_factory=list)

class NewsArticle(BaseModel):
    title: str
    date: str
    url: str
    summary: str

class ReportResponse(BaseModel):
    metrics: Optional[EpidemiologicalMetrics] = None
    charts: Optional[ChartData] = None
    explanation: str = Field(..., description="The Markdown report generated by the LLM")
    news: List[NewsArticle] = Field(default_factory=list, description="Recent news articles referenced in the report")
    execution_log: List[str] = Field(default_factory=list, description="Audit log of agent execution steps")
